### PR TITLE
Update lessons to use Blueprint SDK

### PR DESCRIPTION
**Pull request by Gusarich**
https://github.com/ton-society/ton-footsteps/issues/235

This PR is marked as DRAFT. We should only merge it after all the lessons are successfully updated in both languages.

### CODE REVIEW

**Comment by Gusarich** [comment]
@romanovichim can you please check the update I made for the first lesson? I want to know, if it's good in your opinion. If it is, I'll proceed with the 2nd lesson and then translate them both to English.

**Comment by romanovichim** [comment]
I'll take a look tomorrow and give you feedback.

ср, 7 июн. 2023 г. в 18:35, Daniil Sedov ***@***.***>:

**Comment by romanovichim** [comment]
I looked, it seems that it’s good, the only thing I would add is in the moment where it says that you need Node.js, requirements:[Node.js](https://nodejs.org/) with a recent version like v18, verify version with node -v

**Comment by Gusarich** [comment]
@romanovichim Hi! I've updated the second lesson too. Also updated the sentence about Nodejs version.

Can you please check it? If it's good, I'll translate them both and open a PR in English repo too.

**Comment by Gusarich** [comment]
I also think it will make sense to merge these PRs into some new branches like `blueprint-update` so that we won't have many PRs opened at the same time, and after all the lessons are merged in that branch, you'll be able to merge it into the main branch easily.

**Comment by romanovichim** [comment]
Hello, I also looked at the second lesson, everything is ok, except for the moment exit code: 35 , I think it’s worth explaining why we are checking it and where you can see / understand which exit code is needed in which case.  I also wanted to ask, now I see that you are changing the md in the draft, will you also change the whole code later? 

P.S Plus, I wanted to say thank you for doing it with high quality, because these lessons are important for me)

**Comment by romanovichim** [comment]
I’ll clarify about 35 - you just need to recall that in the smart contract we wrote 35 in throw

**Comment by romanovichim** [comment]
Hi, I looked at the rework of 4 lessons - everything is fine. I wanted to ask: will you add the code after the rework - i.e. blueprint projects in the code folder?

Also, I changed the project structure, but this will be my problem at the time of the merge.

**Comment by Gusarich** [comment]
@romanovichim hi! yes, I'll add the source codes after I finish the rework of all lessons.

I'm almost done, just need to update one more lesson. After than I will review everything few more times, fix docs links, and translate them to English.

**Comment by Gusarich** [comment]
@romanovichim Hi! I reworked the lessons.
Waiting for your review and after that I'm ready to proceed with translating them to English. It won't take much time.

**Comment by romanovichim** [comment]
hi, I'll take a look in the next two days and write back

**Pull request merged**
